const EventPlayersActions = {
  UPDATE_PLAYERS_LOCAL: "UPDATE_PLAYERS_LOCAL",
  UPDATE_PLAYERS_START: "UPDATE_PLAYERS_START",
  UPDATE_PLAYERS_SUCCESS: "UPDATE_PLAYERS_SUCCESS",
  UPDATE_PLAYERS_FAILURE: "UPDATE_PLAYERS_FAILURE",
}

export default EventPlayersActions
