const LocalSettingActionTypes = {
  TOGGLE_THEME: "TOGGLE_THEME",
  CHANGE_THEME_SETTING: "CHANGE_THEME_SETTING",
  UPDATE_SYSTEM_THEME: "UPDATE_SYSTEM_THEME",
  TOGGLE_NAVBAR_ACTIVE: "TOGGLE_NAVBAR_ACTIVE",
  SET_CONTEXT_MENU_ITEMS: "SET_CONTEXT_MENU_ITEMS",
  SHOW_POP_UP_CARD: "SHOW_POP_UP_CARD",
  HIDE_POP_UP_CARD: "HIDE_POP_UP_CARD",
}

export const THEME_SETTING_VALUES = {
  SYSTEM_THEME: "SYSTEM_THEME",
  SELECT_THEME: "SELECT_THEME",
}

export default LocalSettingActionTypes
