const EditActions = {
  EDITOR_EDIT_COLLECTION: "EDITOR_EDIT_COLLECTION",
  EDITOR_COPY_COLLECTION: "EDITOR_COPY_COLLECTION",

  EDITOR_ADD_SLIDE_QUIZ: "EDITOR_ADD_SLIDE_QUIZ",
  EDITOR_ADD_SLIDE_TRUE_FALSE: "EDITOR_ADD_SLIDE_TRUE_FALSE",
  EDITOR_ADD_SLIDE_INPUT: "EDITOR_ADD_SLIDE_INPUT",

  EDITOR_EDIT_SLIDE: "EDITOR_EDIT_SLIDE",
  EDITOR_DUPLICATE_SLIDE: "EDITOR_DUPLICATE_SLIDE",
  EDITOR_DELETE_SLIDE: "EDITOR_DELETE_SLIDE",

  EDITOR_EDIT_OPTION: "EDITOR_EDIT_OPTION",
}

export default EditActions
