const CollectionActions = {
  CREATE_COLLECTION_START: "CREATE_COLLECTION_START",
  CREATE_COLLECTION_SUCCESS: "CREATE_COLLECTION_SUCCESS",
  CREATE_COLLECTION_FAILURE: "CREATE_COLLECTION_FAILURE",

  DELETE_COLLECTION_START: "DELETE_COLLECTION_START",
  DELETE_COLLECTION_SUCCESS: "DELETE_COLLECTION_SUCCESS",
  DELETE_COLLECTION_FAILURE: "DELETE_COLLECTION_FAILURE",

  SAVE_COLLECTION_START: "SAVE_COLLECTION_START",
  SAVE_COLLECTION_SUCCESS: "SAVE_COLLECTION_SUCCESS",
  SAVE_COLLECTION_FAILURE: "SAVE_COLLECTION_FAILURE",

  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
}

export default CollectionActions
