const EventResultsActions = {
  ANALYZE_ANSWERS_START: "ANALYZE_ANSWERS_START",
  ANALYZE_ANSWERS_SUCCESS: "ANALYZE_ANSWERS_SUCCESS",
  ANALYZE_ANSWERS_FAILURE: "ANALYZE_ANSWERS_FAILURE",
}

export default EventResultsActions
