const EventDataActions = {
  CREATE_EVENT_START: "CREATE_EVENT_START",
  CREATE_EVENT_SUCCESS: "CREATE_EVENT_SUCCESS",
  CREATE_EVENT_FAILURE: "CREATE_EVENT_FAILURE",

  START_EVENT_START: "START_EVENT_START",
  START_EVENT_SUCCESS: "START_EVENT_SUCCESS",
  START_EVENT_FAILURE: "START_EVENT_FAILURE",

  EVENT_NEXT_SLIDE_START: "NEXT_SLIDE_START",
  EVENT_NEXT_SLIDE_SUCCESS: "NEXT_SLIDE_SUCCESS",
  EVENT_NEXT_SLIDE_FAILURE: "NEXT_SLIDE_FAILURE",

  UPDATE_DATA_CONNECT_START: "UPDATE_DATA_CONNECT_START",
  UPDATE_DATA_CONNECT_SUCCESS: "UPDATE_DATA_CONNECT_SUCCESS",
  UPDATE_DATA_CONNECT_FAILURE: "UPDATE_DATA_CONNECT_FAILURE",

  UPDATE_DATA_EVENT_START: "UPDATE_DATA_EVENT_START",
  UPDATE_DATA_EVENT_SUCCESS: "UPDATE_DATA_EVENT_SUCCESS",
  UPDATE_DATA_EVENT_FAILURE: "UPDATE_DATA_EVENT_FAILURE",
}
export default EventDataActions

export const STATUS_TYPES = {
  LOBBY: "LOBBY",
  GAME: "GAME",
  GAME_RESULTS: "GAME_RESULTS",
  OVERALL_RESULTS: "OVERALL_RESULTS",
}

export const SLIDE_TYPES = {
  QUIZ: "quiz",
}
